---
language: java
jdk:
  - oraclejdk8

before_script:
  # OS information
  - uname -a

  # CPU information
  - cat /proc/cpuinfo

  # memory information
  - cat /proc/meminfo
  - free -m

  # running process information
  - ps aux

  # disk information
  - df -h

cache:
  directories:
  - $HOME/.m2

before_install:
  - chmod +x mvnw

install:
  - ./mvnw clean install
